services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
