# Generated by Django 5.0.6 on 2024-05-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SP', 'Solar panel'), ('BA', 'Battery'), ('EV', 'Electric vehicle'), ('HP', 'Heat pump'), ('OT', 'Other')], default='OT', max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.home')),
            ],
        ),
    ]
