# Generated by Django 5.0.6 on 2024-05-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('CO', 'Consumer'), ('PR', 'Producer'), ('ST', 'Storage'), ('GR', 'Grid')], default='CO', max_length=2),
        ),
    ]
