# Generated by Django 5.0.6 on 2024-05-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_remove_device_category_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
