# Generated by Django 5.0.6 on 2024-05-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_device_created_at_device_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('constraint_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.device')),
            ],
        ),
    ]
