# Generated by Django 5.0.6 on 2024-05-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_alter_device_capacity_alter_device_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constraint',
            old_name='constraint_type',
            new_name='constraint_direction',
        ),
    ]
