# Generated by Django 5.0.6 on 2024-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_rename_constraint_type_constraint_constraint_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('TI', 'Time'), ('CO', 'Cost'), ('SO', 'Source')], default='TI', max_length=2),
        ),
    ]
