# Generated by Django 5.0.6 on 2024-05-15 18:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_constraint_constraint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.home')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('power', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.device')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.schedule')),
            ],
        ),
    ]
