# Generated by Django 5.0.6 on 2024-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_constraint_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('TI', 'Time'), ('CO', 'Cost'), ('SO', 'Source'), ('PO', 'Power')], default='TI', max_length=2),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='stop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
