# Generated by Django 5.0.6 on 2024-05-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_alter_constraint_constraint_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='home',
        ),
        migrations.RemoveField(
            model_name='scheduleelement',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleelement',
            name='device',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleElement',
        ),
    ]
