# Generated by Django 5.0.6 on 2024-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0015_device_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='power_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='source_in',
            field=models.CharField(blank=True, choices=[('PV', 'Photovoltaic'), ('BA', 'Battery'), ('GR', 'Grid')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='source_out',
            field=models.CharField(blank=True, choices=[('PV', 'Photovoltaic'), ('BA', 'Battery'), ('GR', 'Grid')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='start_price_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='start_price_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='start_time_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='start_time_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stop_price_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stop_price_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stop_time_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stop_time_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
    ]
