# Generated by Django 5.0.6 on 2024-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_alter_device_source_in_alter_device_source_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
