x-app: &app
  image: ghcr.io/floriandejonckheere/zapp/app:latest
  networks:
    - fcloud
  environment:
    SECRET_KEY: ${SECRET_KEY}
    PG_USER: ${PG_USER}
    PG_PASSWORD: ${PG_PASSWORD}
    PG_DATABASE: ${PG_DATABASE}
  logging:
    driver: "json-file"
    options:
      max-file: "1"
      max-size: "128m"
      compress: "true"
  restart: unless-stopped

services:
  app:
    <<: *app

  migration:
    <<: *app
    command: python manage.py migrate
    restart: "no"

  web:
    image: ghcr.io/floriandejonckheere/zapp/web:latest
    networks:
      - fcloud
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "128m"
        compress: "true"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.zapp-tls.redirectscheme.scheme: "https"

      traefik.http.routers.zapp.rule: "Host(`zapp.dejonckhee.re`)"
      traefik.http.routers.zapp.entrypoints: "web"
      traefik.http.routers.zapp.middlewares: "zapp-tls"

      traefik.http.routers.zapp-tls.rule: "Host(`zapp.dejonckhee.re`)"
      traefik.http.routers.zapp-tls.entrypoints: "websecure"
      traefik.http.routers.zapp-tls.tls: "true"
      traefik.http.routers.zapp-tls.tls.certresolver: "letsencrypt"

      traefik.http.services.zapp.loadbalancer.server.port: "80"

networks:
  fcloud:
    external: true
    name: "fcloud_default"
