name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'production'

jobs:
  app:
    name: Continuous Integration (app)
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true

  web:
    name: Continuous Integration (web)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn set version 4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn tsc

      - name: Build
        run: yarn build

  build-app:
    name: Continuous Integration (build-app)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs:
      - app

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push app to GitHub Packages
        uses: docker/build-push-action@v5.3.0
        with:
          target: app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/app:latest

  build-web:
    name: Continuous Integration (build-web)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs:
      - web

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push app to GitHub Packages
        uses: docker/build-push-action@v5.3.0
        with:
          target: web
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/web:latest

  deploy-app:
    name: Continuous Deployment (app)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://zap.dejonckhee.re
    needs:
        - build-app

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up docker context
        uses: amirmarmul/docker-context-ssh-action@v2
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-private-key: ${{ secrets.SSH_KEY }}
          context-name: cloud
          context-use: true

      - name: Set environment
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "PG_USER=${{ secrets.PG_USER }}" >> $GITHUB_ENV
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> $GITHUB_ENV
          echo "PG_DATABASE=${{ secrets.PG_DATABASE }}" >> $GITHUB_ENV
      - name: Deploy application
        env:
          GHCR_USER: ${{ secrets.GHCR_TOKEN }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          COMPOSE_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          cd ops
          docker compose pull
          docker compose up migration
          docker compose up --detach app web
