name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'production'

jobs:
  app:
    name: Continuous Integration (app)
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true

  web:
    name: Continuous Integration (web)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn tsc

      - name: Build
        run: yarn build
