name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'production'

jobs:
  app:
    name: Continuous Integration (app)
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true

  web:
    name: Continuous Integration (web)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn tsc

      - name: Build
        run: yarn build

  build-app:
    name: Continuous Integration (build-app)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs:
      - app

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push app to GitHub Packages
        uses: docker/build-push-action@v5.3.0
        with:
          target: app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/app:latest

  build-web:
    name: Continuous Integration (build-web)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs:
      - web

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push app to GitHub Packages
        uses: docker/build-push-action@v5.3.0
        with:
          target: web
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/web:latest
